{{- if and .Values.mapproxy.enabled .Values.mapproxy.wms.enabled -}}

{{- $releaseName := .Release.Name -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $type := "wms"}}
{{- $replicaCount := .Values.mapproxy.wms.replicaCount }}
{{- $wmsDeploymentName := include "wms-deployment.fullname" . }}


{{- if .Values.authentication.ssl.enabled }}
{{- if and .Values.authentication.ssl.useExternal (not .Values.authentication.ssl.externalSecretName) }}
{{- fail "When using external ssl secret the value for .Values.authentication.ssl.externalSecretName should be set" }}
{{- end }}
{{- end }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $wmsDeploymentName }}
  annotations:
    collectord.io/index: {{ quote .Values.splunkIndex }}
    collectord.io/output: splunk
  labels:
    app: {{ $chartName }}
    component: {{ $chartName }}
    environment: {{ include "mapproxy.environment" . }}
    release: {{ $releaseName }}
    {{- include "mapproxy.labels" . | nindent 4 }}
spec:
  {{- template "mapproxy-chart.mapproxy-bundle" (merge (dict "releaseName" $releaseName "chartName" $chartName "type" $type "replicaCount" $replicaCount "resources" .Values.mapproxy.wms.resources) .)}}
{{- end -}}
