{{- if .Values.mapproxy.enabled -}}
{{- $chartName := include "mapproxy.name" . -}}
{{- $releaseName := .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $releaseName }}-configmap
  labels:
    app: {{ $releaseName }}-{{ $chartName }}
    component: map-proxy-configmap
    environment: {{ .Values.environment }}
    release: {{ $releaseName }}
data:
  S3_ENDPOINT_URL: {{ .Values.rasterCommon.storage.s3.endpointUrl | quote }}
  S3_BUCKET:  {{ .Values.rasterCommon.storage.s3.tilesBucket | quote }}
  AWS_HTTPS: {{ .Values.rasterCommon.storage.s3.awsHttps | quote }}
  TELEMETRY_METRICS_ENABLED: {{ .Values.global.metrics.enabled | quote }}
  TELEMETRY_TRACING_ENABLED: {{ .Values.global.tracing.enabled | quote }}
  TELEMETRY_TRACING_ENDPOINT: {{ .Values.global.tracing.url | quote }}
  TELEMETRY_TRACING_SAMPLING_RATIO_DENOMINATOR: {{ .Values.global.tracing.samplingRatioDenominator | quote }}
{{- end }}
