{
 "title": "uWSGI",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(uwsgi_up, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "UP Overview",
   "type": "stat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "uwsgi_up", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Listen queue",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "uwsgi_listen_queue_length{instance=~\"$instance\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Request / s",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "irate(uwsgi_worker_requests_total{instance=~\"$instance\"}[5m])",
     "legendFormat": "{{job}}_worker_{{worker_id}}"
    }
   ]
  },
  {
   "title": "Accepting request ",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uwsgi_worker_accepting{instance=~\"$instance\"}",
     "legendFormat": "{{job}}_worker_{{worker_id}}"
    }
   ]
  },
  {
   "title": "Business",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "uwsgi_worker_busy{instance=~\"$instance\"}",
     "legendFormat": "{{job}}_worker_{{worker_id}}"
    }
   ]
  },
  {
   "title": "Harakiri count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "uwsgi_worker_harakiri_count_total{instance=~\"$instance\"}",
     "legendFormat": "{{job}}_worker_{{worker_id}}"
    }
   ]
  },
  {
   "title": "Respawn count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "uwsgi_worker_respawn_count_total{instance=~\"$instance\"}",
     "legendFormat": "{{job}}_worker_{{worker_id}}"
    }
   ]
  }
 ]
}