apiVersion: v2
name: mapproxy
description: A Helm chart for mapproxy service
type: application
version: 2.0.1
appVersion: 2.0.1
dependencies:
  - name: nginx
    version: 1.1.0
    repository: oci://acrarolibotnonprod.azurecr.io/helm
